"""
Photo upload schemas — the core V1 data exchange format.

ARCHITECTURE:
    The mobile app sends:
        1. An encrypted photo blob (AES-256, server cannot read it)
        2. A list of face detections with protected embeddings

    Each face detection includes the 512-d protected embedding that has
    already been through: MobileFaceNet -> L2 norm -> feature subtraction -> re-norm.
    The server stores these and later runs HDBSCAN on them.
"""

from pydantic import BaseModel, Field


class FaceEmbeddingPayload(BaseModel):
    """A single face detection from the mobile app.

    The mobile app runs SCRFD detection and MobileFaceNet embedding
    on-device, applies feature subtraction, then sends this payload.
    """
    face_index: int = Field(..., description="Index of this face within the photo (0-based)")
    bbox: list[int] = Field(..., min_length=4, max_length=4, description="Bounding box [x1, y1, x2, y2]")
    det_score: float = Field(..., ge=0.0, le=1.0, description="SCRFD detection confidence")
    embedding: list[float] = Field(
        ...,
        min_length=512,
        max_length=512,
        description="512-d protected embedding (feature-subtracted, L2-normalised)",
    )


class PhotoUploadRequest(BaseModel):
    """Request body for uploading a single photo with its face detections.

    The encrypted blob is sent as a separate multipart file.
    This JSON body accompanies it with the metadata and embeddings.
    """
    photo_id: str = Field(..., description="UUID generated by the mobile app")
    original_filename: str = Field(default="", description="Original filename for display")
    faces: list[FaceEmbeddingPayload] = Field(
        default=[],
        description="Face detections with protected embeddings from on-device processing",
    )


class PhotoUploadResponse(BaseModel):
    """Returned after a photo is successfully uploaded and stored."""
    photo_id: str
    faces_stored: int
    status: str
